apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vqn5h0ool-dotnet-basic
  janus-idp.io/tekton: vqn5h0ool-dotnet-basic
  backstage.io/kubernetes-id: vqn5h0ool-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vqn5h0ool-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
